# Generated by Django 5.2.5 on 2025-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
