# Generated by Django 5.2.5 on 2025-08-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_event_image_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
