# Generated by Django 5.2.5 on 2025-08-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_event_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
