# Generated by Django 5.2.5 on 2025-08-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
            ],
            options={
                'verbose_name': 'Membro da Diretoria',
                'verbose_name_plural': 'Membros da Diretoria',
            },
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('responsible_professors', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grupo de Pesquisa',
                'verbose_name_plural': 'Grupos de Pesquisa',
            },
        ),
    ]
