# Generated by Django 5.2.5 on 2025-08-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='entity_logos/')),
            ],
            options={
                'verbose_name': 'Entidade Discente',
                'verbose_name_plural': 'Entidades Discentes',
            },
        ),
    ]
