# Generated by Django 5.2.5 on 2025-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_studententity'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='research_groups/'),
        ),
    ]
