# Generated by Django 5.2.5 on 2025-08-19 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_researchgroup_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandato', models.CharField(help_text='Ex: 2025/2026', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Diretoria',
                'verbose_name_plural': 'Diretorias',
                'ordering': ['-mandato'],
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['role'], 'verbose_name': 'Membro da Diretoria', 'verbose_name_plural': 'Membros da Diretoria'},
        ),
        migrations.AddField(
            model_name='member',
            name='diretoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='team.diretoria'),
        ),
    ]
