# Generated by Django 5.2.5 on 2025-08-19 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_diretoria_alter_member_options_member_diretoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretoriaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Presidência, Tesouraria, etc.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Cargo da Diretoria',
                'verbose_name_plural': 'Cargos da Diretoria',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='diretoria',
        ),
        migrations.AddField(
            model_name='member',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='team.diretoriacargo'),
        ),
        migrations.DeleteModel(
            name='Diretoria',
        ),
    ]
