# Generated by Django 5.2.5 on 2025-08-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_diretoriacargo_remove_member_diretoria_member_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mandato', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Gestão Histórica',
                'verbose_name_plural': 'Gestões Históricas',
                'ordering': ['-mandato'],
            },
        ),
        migrations.CreateModel(
            name='MembroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membros_historicos/')),
                ('gestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='team.gestaohistorico')),
            ],
            options={
                'verbose_name': 'Membro Histórico',
                'verbose_name_plural': 'Membros Históricos',
            },
        ),
    ]
