# Generated by Django 5.2.5 on 2025-08-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_gestaohistorico_membrohistorico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membrohistorico',
            options={'ordering': ['name'], 'verbose_name': 'Membro Histórico', 'verbose_name_plural': 'Membros Históricos'},
        ),
    ]
