# Generated by Django 5.2.5 on 2025-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Estatuto do CASI', max_length=200)),
                ('file', models.FileField(upload_to='estatuto/')),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estatuto',
                'verbose_name_plural': 'Estatuto',
            },
        ),
        migrations.CreateModel(
            name='RegimentoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Regimento Interno do CASI', max_length=200)),
                ('file', models.FileField(upload_to='regimento/')),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regimento Interno',
                'verbose_name_plural': 'Regimento Interno',
            },
        ),
    ]
