# Generated by Django 5.2.5 on 2025-08-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_estatuto_regimentointerno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatuto',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Estatuto', 'verbose_name_plural': 'Estatuto'},
        ),
        migrations.AlterModelOptions(
            name='regimentointerno',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Regimento Interno', 'verbose_name_plural': 'Regimento Interno'},
        ),
    ]
